import type { ThemePreset } from "../types/theme";

export const toolkitTheme: ThemePreset = {
  label: "Toolkit",
  createdAt: "2025-12-09",
  styles: {
    light: {
      background: "#f1f5f9",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      popover: "#ffffff",
      "popover-foreground": "#0f172a",
      primary: "#1e3a8a",
      "primary-foreground": "#ffffff",
      secondary: "#f1f5f9",
      "secondary-foreground": "#0f172a",
      muted: "#f1f5f9",
      "muted-foreground": "#475569",
      accent: "#FCC601",
      "accent-foreground": "#0f172a",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#94a3b8",
      input: "#f1f5f9",
      ring: "#3b82f6",
      "chart-1": "#3b82f6",
      "chart-2": "#60a5fa",
      "chart-3": "#34d399",
      "chart-4": "#fbbf24",
      "chart-5": "#f87171",
      sidebar: "#020617",
      "sidebar-foreground": "#f1f5f9",
      "sidebar-primary": "#3b82f6",
      "sidebar-primary-foreground": "#f1f5f9",
      "sidebar-accent": "#FCC601",
      "sidebar-accent-foreground": "#0f172a",
      "sidebar-border": "#1e293b",
      "sidebar-ring": "#FCC601",
      "font-sans": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
      "font-serif": 'Georgia, Cambria, "Times New Roman", Times, serif',
      "font-mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      radius: "0.75rem",
      "shadow-color": "hsl(222 47% 11%)",
      "shadow-opacity": "0.1",
      "shadow-blur": "20px",
      "shadow-spread": "0px",
      "shadow-offset-x": "0px",
      "shadow-offset-y": "4px",
      "letter-spacing": "-0.01em",
      spacing: "0.25rem",
    },
    dark: {
      background: "#0f172a",
      foreground: "#f1f5f9",
      card: "#1e293b",
      "card-foreground": "#f1f5f9",
      popover: "#1e293b",
      "popover-foreground": "#f1f5f9",
      primary: "#3b82f6",
      "primary-foreground": "#0f172a",
      secondary: "#1e293b",
      "secondary-foreground": "#f1f5f9",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      accent: "#FCC601",
      "accent-foreground": "#0f172a",
      destructive: "#ef4444",
      "destructive-foreground": "#0f172a",
      border: "#334155",
      input: "#1e293b",
      ring: "#3b82f6",
      "chart-1": "#3b82f6",
      "chart-2": "#60a5fa",
      "chart-3": "#34d399",
      "chart-4": "#fbbf24",
      "chart-5": "#f87171",
      sidebar: "#020617",
      "sidebar-foreground": "#f1f5f9",
      "sidebar-primary": "#3b82f6",
      "sidebar-primary-foreground": "#f1f5f9",
      "sidebar-accent": "#FCC601",
      "sidebar-accent-foreground": "#0f172a",
      "sidebar-border": "#1e293b",
      "sidebar-ring": "#FCC601",
      "font-sans": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
      "font-serif": 'Georgia, Cambria, "Times New Roman", Times, serif',
      "font-mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      radius: "0.75rem",
      "shadow-color": "hsl(222 47% 5%)",
      "shadow-opacity": "0.25",
      "shadow-blur": "20px",
      "shadow-spread": "0px",
      "shadow-offset-x": "0px",
      "shadow-offset-y": "4px",
      "letter-spacing": "-0.01em",
      spacing: "0.25rem",
    },
  },
};
